### PR TITLE
Multiplayer menu fixes

### LINKED ISSUE #223: Close multiplayer menu with ESC
## Summary
When pressing ESC, instead of closing the menu, you open the pause menu. This is somewhat unexpected.

Additionally I think the Multiplayer menu should either be duplicated or completely moved to the pause screen. Makes much more sense having it there.
At least the Host Game button.

### PR DESCRIPTION
**Pull request by botprizm**
Fixes #223.

Fixed multiplayer menu so that it now closes when pressing escape.

Moved the multiplayer menu to the pause menu replacing the resume game button. 

Result:
CSM-hostgame

### CODE REVIEW

**Comment by botprizm** [comment]
Fixes #223

File: src/Extensions/LoadingExtension.cs [hunk 1]
```diff
@@ -36,36 +34,19 @@ public override void OnLevelLoaded(LoadMode mode)
...
-            _multiplayerButton.pressedBgSprite = "ButtonMenuPressed";
-            _multiplayerButton.textColor = new Color32(255, 255, 255, 255);
-            _multiplayerButton.disabledTextColor = new Color32(7, 7, 7, 255);
-            _multiplayerButton.hoveredTextColor = new Color32(7, 132, 255, 255);
-            _multiplayerButton.focusedTextColor = new Color32(255, 255, 255, 255);
-            _multiplayerButton.pressedTextColor = new Color32(30, 30, 44, 255);
-
-            // Enable button sounds.
-            _multiplayerButton.playAudioEvents = true;
+            UIButton resumeButton = UIView.GetAView()?.FindUIComponent("Resume") as UIButton;
```
Comment (kaenganxt) [inline src/Extensions/LoadingExtension.cs]: I don't think we should replace the Resume button but rather add another button to the list.

File: src/Panels/HostGamePanel.cs [hunk 2]
```diff
@@ -111,6 +111,15 @@ public override void Start()
             };
         }
 
+        public override void Update()
```
Comment (kaenganxt) [inline src/Panels/HostGamePanel.cs:114]: Add this logic also to the ConnectionPanel (which is opened instead of the HostGamePanel when the server is running)

**Review by kaenganxt — CHANGES_REQUESTED** [review]
Thank you! Looks mostly good. Please resolve the mentioned issues before the pr can be merged.

File: src/Extensions/LoadingExtension.cs (hunk 1 above)
Comment (rocketboy00) [reply src/Extensions/LoadingExtension.cs:37]: Where do think the button should be added instead? Under the resume button?

Comment (botprizm) [reply src/Extensions/LoadingExtension.cs]: Where do you think the button should be instead? Under it?

Comment (kaenganxt) [reply src/Extensions/LoadingExtension.cs]: Yes, I think below would be good.

Comment (botprizm) [reply src/Extensions/LoadingExtension.cs]: Made two version.
CSM-pauseMenu
thumbnail_CSM-multiplayerBtn-2

Comment (kaenganxt) [reply src/Extensions/LoadingExtension.cs]: Seeing this, I think I prefer the first version. What do you think?
And to other people reading this: Do you have any opinion?

Comment (botprizm) [reply src/Extensions/LoadingExtension.cs]: Yeah I also prefer the first one, it's easier to notice and I think it overall makes more sense.

Comment (botprizm) [reply src/Extensions/LoadingExtension.cs]: Added the first version

**Review by kaenganxt — APPROVED** [review]
Looks good, thank you for your contribution!
